# Generated by Django 3.2.5 on 2021-08-12 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='Artist_follow',
            new_name='artist_follow',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='Artist_name_EN',
            new_name='artist_name_EN',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='Artist_name_TH',
            new_name='artist_name_TH',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='Artist_picture',
            new_name='artist_picture',
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_header', models.CharField(max_length=50)),
                ('request_type', models.CharField(max_length=50)),
                ('request_detail', models.CharField(max_length=200)),
                ('newuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
