# Generated by Django 3.2.5 on 2021-08-12 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210812_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='Date_add',
            new_name='date_add',
        ),
    ]
