# Generated by Django 3.2.5 on 2021-08-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210814_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_detail',
            field=models.IntegerField(default=1),
        ),
    ]
