# Generated by Django 3.2.5 on 2021-08-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_request_request_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_detail',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.IntegerField(default=1),
        ),
    ]
