# Generated by Django 3.2.5 on 2021-08-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210814_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_detail',
            field=models.TextField(default='no_detail'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_detail',
            field=models.TextField(),
        ),
    ]
