# Generated by Django 3.2.5 on 2021-08-16 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210814_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ticket_end',
        ),
    ]
