# Generated by Django 3.2.5 on 2021-08-16 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_event_ticket_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ticekt_price',
            new_name='ticket_price',
        ),
    ]
