# Generated by Django 3.2.5 on 2021-08-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_ticekt_price_event_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_picture',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
