# Generated by Django 3.2.5 on 2021-10-06 20:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_artist_artist_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessKey', models.CharField(max_length=100)),
                ('secretKey', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Noification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eventfollow')),
            ],
        ),
        migrations.RemoveField(
            model_name='ticketevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='ticketevent',
            name='ticket',
        ),
        migrations.AddField(
            model_name='artist',
            name='chat_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='artistpost',
            field=models.ManyToManyField(blank=True, to='api.Artist'),
        ),
        migrations.AddField(
            model_name='event',
            name='complete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='ticketpost',
            field=models.ManyToManyField(blank=True, to='api.Ticket'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='expo_noti',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='ticket',
            name='detail',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='venue',
            name='mapname',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='venue',
            name='mapurl',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='artist',
            name='date_add',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='artistfollow',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_lastupdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='event',
            name='detail_update',
            field=models.CharField(default='เพิ่มข้อมูลเข้าสู่ระบบ', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='promoter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.promoter'),
        ),
        migrations.AlterField(
            model_name='event',
            name='show_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_open',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.venue'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='ArtistEvent',
        ),
        migrations.DeleteModel(
            name='TicketEvent',
        ),
    ]
